// Full-canvas narrative event overlay, drawn over the paused (dimmed) world.
//
// Shows a Victorian field-journal entry generated by the NarrativeEngine, with
// two choice buttons. While the API call is still in flight it shows an animated
// loading line instead. Records button rects so main.js can hitTest() pointer
// events and resolve the chosen consequence. Pure canvas rendering — no DOM.
//
// Layout is a measured top-down "flex column": title → divider → narrative →
// choice buttons, each section placed below the previous one's true height.
// Because buttons sit relative to where the narrative ends (never anchored to a
// fixed bottom), they can't overlap the body on narrow phones. The panel grows
// to fit its content, is clamped to the viewport, and is clipped to its rounded
// border so no text can bleed outside the card.

import { COLORS, FONTS, font, text, panel, rgba, roundRectPath } from '../utils/renderer.js';
import { isBeneficialConsequence } from '../narrative/NarrativeEngine.js';

const PANEL_RADIUS = 14;

export class EventUI {
  constructor() {
    this._buttons = []; // { index, x, y, w, h }
  }

  /** Returns the chosen choice index, or null if (x,y) hit nothing. */
  hitTest(px, py) {
    for (const b of this._buttons) {
      if (px >= b.x && px <= b.x + b.w && py >= b.y && py <= b.y + b.h) {
        return b.index;
      }
    }
    return null;
  }

  draw(ctx, event, loading, w, h) {
    this._buttons = [];

    ctx.save();

    // Dim the world underneath.
    ctx.fillStyle = 'rgba(20, 18, 16, 0.78)';
    ctx.fillRect(0, 0, w, h);

    // Responsive width; narrow viewports (phones) stack the choice buttons.
    const pw = Math.min(w - 24, 460);
    const stacked = pw < 440;
    const padX = 22;
    const innerW = pw - padX * 2;

    // ---- Loading state: fixed-height card, no body to measure yet. ----
    if (!event) {
      const ph = Math.min(h - 24, 220);
      const px = (w - pw) / 2;
      const py = (h - ph) / 2;
      panel(ctx, px, py, pw, ph, { fill: COLORS.parchment, stroke: COLORS.ink, lineWidth: 3, radius: PANEL_RADIUS });
      this._drawQuill(ctx, px + pw / 2, py + 44);
      const dots = '.'.repeat(1 + Math.floor((Date.now() / 400) % 3));
      text(ctx, `Consulting the field notes${dots}`, px + pw / 2, py + ph / 2 + 12, {
        fontStr: `italic ${font(FONTS.body, 14)}`,
        color: rgba(COLORS.ink, 0.7),
      });
      ctx.restore();
      return;
    }

    // ---- Measure content so the panel grows to fit (no overlap, no bleed). ----
    const titleFont = font(FONTS.title, stacked ? 19 : 22, '600');
    const bodyFont = font(FONTS.body, stacked ? 13 : 14);
    const bodyLH = stacked ? 18 : 19;
    const bodyLines = this._wrapLines(ctx, event.text, Math.min(innerW, 420), bodyFont);

    const choices = event.choices.slice(0, 2);
    const btnGap = 10;

    // Pre-wrap each consequence description so the choice buttons grow to fit it
    // (label on top, wrapped consequence below). Both buttons share the tallest
    // height so a side-by-side row stays aligned, and the text never bleeds out.
    const consFont = font(FONTS.mono, 11, '700');
    const consLH = 14;
    const btnW0 = stacked ? innerW : (innerW - btnGap) / 2;
    const consWrapW = btnW0 - 24; // cardWidth − 24px padding
    const choiceConsLines = choices.map((c) => {
      const cons = c.consequence;
      return cons && cons.description ? this._wrapLines(ctx, cons.description, consWrapW, consFont) : [];
    });
    const maxConsLines = Math.max(1, ...choiceConsLines.map((l) => l.length));
    const btnH = 28 + maxConsLines * consLH; // label band + wrapped consequence

    // Section heights, top to bottom.
    const topPad = 16;
    const quillH = 30;
    const titleH = stacked ? 26 : 30;
    const dividerGap = 14;
    const afterDivider = 14;
    const bodyH = bodyLines.length * bodyLH;
    const beforeButtons = 18;
    const buttonsH = stacked ? btnH * choices.length + btnGap * (choices.length - 1) : btnH;
    const bottomPad = 18;

    const contentH =
      topPad + quillH + titleH + dividerGap + afterDivider + bodyH + beforeButtons + buttonsH + bottomPad;

    // Card never taller than the viewport; clipped to its border below.
    const ph = Math.min(contentH, h - 24);
    const px = (w - pw) / 2;
    const py = (h - ph) / 2;

    panel(ctx, px, py, pw, ph, { fill: COLORS.parchment, stroke: COLORS.ink, lineWidth: 3, radius: PANEL_RADIUS });

    // Clip to the rounded panel so nothing can bleed past the border.
    ctx.save();
    roundRectPath(ctx, px, py, pw, ph, PANEL_RADIUS);
    ctx.clip();

    let cy = py + topPad;

    // Quill-in-journal illustration.
    this._drawQuill(ctx, px + pw / 2, cy + 14);
    cy += quillH;

    // Title.
    text(ctx, event.title, px + pw / 2, cy + titleH / 2, { fontStr: titleFont, color: COLORS.ink });
    cy += titleH + dividerGap;

    // Divider.
    ctx.strokeStyle = rgba(COLORS.ink, 0.4);
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(px + 36, cy);
    ctx.lineTo(px + pw - 36, cy);
    ctx.stroke();
    cy += afterDivider;

    // Narrative body — each wrapped line on its own row, centered.
    bodyLines.forEach((ln, i) => {
      text(ctx, ln, px + pw / 2, cy + i * bodyLH + bodyLH / 2, { fontStr: bodyFont, color: COLORS.ink });
    });
    cy += bodyH + beforeButtons;

    // Choice buttons — laid relative to the narrative's end, so they can never
    // overlap the body. Stacked on phones, side by side on wider screens.
    const btnTop = cy;
    choices.forEach((choice, i) => {
      let bx;
      let by;
      let bw;
      if (stacked) {
        bw = innerW;
        bx = px + padX;
        by = btnTop + i * (btnH + btnGap);
      } else {
        bw = (innerW - btnGap) / 2;
        bx = px + padX + i * (bw + btnGap);
        by = btnTop;
      }
      this._drawChoice(ctx, choice, choiceConsLines[i], bx, by, bw, btnH);
      this._buttons.push({ index: i, x: bx, y: by, w: bw, h: btnH });
    });

    ctx.restore(); // clip
    ctx.restore(); // root
  }

  _drawChoice(ctx, choice, consLines, x, y, w, h) {
    panel(ctx, x, y, w, h, {
      fill: rgba(COLORS.gold, 0.1),
      stroke: COLORS.ink,
      lineWidth: 1.6,
      radius: 8,
    });
    const cx = x + w / 2;
    const maxW = w - 24; // inner padding so text never touches the button edge

    // Choice button text.
    const labelFont = font(FONTS.title, 16, '700');
    text(ctx, this._fit(ctx, choice.label, maxW, labelFont), cx, y + 16, {
      fontStr: labelFont,
      color: COLORS.ink,
    });

    // Consequence outcome — wrapped within the card, colored by benefit. (The
    // old italic `choice.description` line rendered "undefined" — choices carry
    // no such field — so it is gone; only label + consequence.description show.)
    if (consLines && consLines.length) {
      const good = isBeneficialConsequence(choice.consequence);
      const consFont = font(FONTS.mono, 11, '700');
      const consLH = 14;
      const startY = y + 34;
      consLines.forEach((ln, i) => {
        text(ctx, ln, cx, startY + i * consLH, {
          fontStr: consFont,
          color: good ? COLORS.gold : COLORS.crimson,
        });
      });
    }
  }

  // Small quill-in-journal illustration, centered at (cx, cy).
  _drawQuill(ctx, cx, cy) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.strokeStyle = COLORS.ink;
    ctx.lineWidth = 1.4;
    // open journal
    ctx.fillStyle = rgba(COLORS.parchmentSoft, 1);
    ctx.beginPath();
    ctx.moveTo(-22, 8);
    ctx.quadraticCurveTo(0, 2, 22, 8);
    ctx.lineTo(22, 14);
    ctx.quadraticCurveTo(0, 8, -22, 14);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    // spine
    ctx.beginPath();
    ctx.moveTo(0, 5);
    ctx.lineTo(0, 12);
    ctx.stroke();
    // quill (diagonal feather)
    ctx.beginPath();
    ctx.moveTo(-2, 6);
    ctx.lineTo(16, -16);
    ctx.stroke();
    ctx.fillStyle = rgba(COLORS.ink, 0.85);
    ctx.beginPath();
    ctx.moveTo(16, -16);
    ctx.quadraticCurveTo(10, -10, 7, -6);
    ctx.quadraticCurveTo(13, -10, 16, -16);
    ctx.fill();
    ctx.restore();
  }

  // Word-wrap `str` into an array of lines that each fit within maxWidth.
  _wrapLines(ctx, str, maxWidth, fontStr) {
    ctx.save();
    ctx.font = fontStr;
    const words = String(str).split(/\s+/).filter(Boolean);
    const lines = [];
    let cur = '';
    for (const word of words) {
      const test = cur ? `${cur} ${word}` : word;
      if (ctx.measureText(test).width > maxWidth && cur) {
        lines.push(cur);
        cur = word;
      } else {
        cur = test;
      }
    }
    if (cur) lines.push(cur);
    ctx.restore();
    return lines;
  }

  // Truncate `str` with an ellipsis so it fits within maxWidth at the given font.
  _fit(ctx, str, maxWidth, fontStr) {
    const s = String(str);
    ctx.save();
    ctx.font = fontStr;
    if (ctx.measureText(s).width <= maxWidth) {
      ctx.restore();
      return s;
    }
    let lo = 0;
    let hi = s.length;
    while (lo < hi) {
      const mid = Math.ceil((lo + hi) / 2);
      if (ctx.measureText(`${s.slice(0, mid)}…`).width <= maxWidth) lo = mid;
      else hi = mid - 1;
    }
    ctx.restore();
    return `${s.slice(0, lo).trimEnd()}…`;
  }
}
